server:
  port: 8101

spring:
  application:
    name: BarberNotes
  config:
    import: optional:file:.env[.properties]

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    parameters:
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

logging:
    level:
      org.springframework.security: DEBUG
      root: info
      kg.barbernotes.barbernotes: debug
      com.zaxxer.hikari: error
      org.apache.tomcat: error
      liquibase: info
    file:
      path: logs
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET}
    customer:
      access-ttl-minutes: 60
      refresh-ttl-minutes: 43200
    staff:
      access-ttl-minutes: 15
      refresh-ttl-minutes: 10080