package kg.barbernotes.barbernotes.common.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    INVALID_INPUT("INVALID_INPUT", HttpStatus.BAD_REQUEST),
    VALIDATION_FAILED("VALIDATION_FAILED", HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION("INVALID_STATUS_TRANSITION", HttpStatus.BAD_REQUEST),

    // 404 Not Found
    BRANCH_NOT_FOUND("BRANCH_NOT_FOUND", HttpStatus.NOT_FOUND),
    SERVICE_CATEGORY_NOT_FOUND("SERVICE_CATEGORY_NOT_FOUND", HttpStatus.NOT_FOUND),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND", HttpStatus.NOT_FOUND),
    BARBER_NOT_FOUND("BARBER_NOT_FOUND", HttpStatus.NOT_FOUND),
    BARBER_SERVICE_NOT_FOUND("BARBER_SERVICE_NOT_FOUND", HttpStatus.NOT_FOUND),
    SERVICE_NOT_FOUND("SERVICE_NOT_FOUND", HttpStatus.NOT_FOUND),
    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND", HttpStatus.NOT_FOUND),
    WORK_SHIFT_NOT_FOUND("ENTITY_NOT_FOUND", HttpStatus.NOT_FOUND),
    APPOINTMENT_NOT_FOUND("APPOINTMENT_NOT_FOUND", HttpStatus.NOT_FOUND),


    // 409 Conflict
    ENTITY_ALREADY_EXISTS("ENTITY_ALREADY_EXISTS", HttpStatus.CONFLICT),
    BARBER_SERVICE_ALREADY_EXISTS("BARBER_SERVICE_ALREADY_EXISTS", HttpStatus.CONFLICT),
    ADDRESS_ALREADY_EXISTS("ADDRESS_ALREADY_EXISTS", HttpStatus.CONFLICT),
    NAME_ALREADY_EXISTS("NAME_ALREADY_EXISTS", HttpStatus.CONFLICT),
    SHIFT_ALREADY_EXISTS("SHIFT_ALREADY_EXISTS", HttpStatus.CONFLICT),
    SHIFT_HAS_APPOINTMENTS("SHIFT_HAS_APPOINTMENTS", HttpStatus.CONFLICT),
    SCHEDULE_CONFLICT("SCHEDULE_CONFLICT", HttpStatus.CONFLICT),
    OPTIMISTIC_LOCK_CONFLICT("OPTIMISTIC_LOCK_CONFLICT", HttpStatus.CONFLICT),

    // 500 Internal Server Error
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    BUSINESS_RULE_VIOLATION("BUSINESS_RULE_VIOLATION", HttpStatus.UNPROCESSABLE_ENTITY);















    private final String code;
    private final HttpStatus httpStatus;
}
